import {useEffect,useMemo,useState} from 'react';
import {Alert,AppBar,Box,Button,Card,CardContent,Chip,Container,CssBaseline,FormControl,Grid,IconButton,InputLabel,MenuItem,Select,Stack,Table,TableBody,TableCell,TableContainer,TableHead,TableRow,Toolbar,Typography,createTheme,ThemeProvider} from '@mui/material';
import {DarkMode,LightMode,FileDownload} from '@mui/icons-material';
import {Line} from 'react-chartjs-2'; import {Chart as ChartJS,CategoryScale,LinearScale,PointElement,LineElement,Tooltip,Legend,Filler} from 'chart.js';
import {getBoxBenchmarks,getPrices} from './api'; import type {BoxBenchmark,Price} from './types';
ChartJS.register(CategoryScale,LinearScale,PointElement,LineElement,Tooltip,Legend,Filler);
const products=['','FRESH_ORANGE','INDUSTRIAL_ORANGE','FCOJ','NFC'];
function App(){const [dark,setDark]=useState(true),[product,setProduct]=useState(''),[prices,setPrices]=useState<Price[]>([]),[benchmarks,setBenchmarks]=useState<BoxBenchmark[]>([]),[error,setError]=useState('');
 const theme=useMemo(()=>createTheme({palette:{mode:dark?'dark':'light',primary:{main:'#ff8a1f'},background:{default:dark?'#0c1117':'#f5f7fa',paper:dark?'#151d27':'#fff'}},shape:{borderRadius:14},typography:{fontFamily:'Inter,system-ui,sans-serif',h4:{fontWeight:800}}}),[dark]);
 useEffect(()=>{getPrices({country:'CN',product:product||undefined,size:500}).then(p=>{setPrices(p.content);setError('')}).catch(()=>setError('API indisponível. Confirme se o backend e o PostgreSQL estão ativos.'))},[product]);
 useEffect(()=>{getBoxBenchmarks().then(setBenchmarks).catch(()=>setBenchmarks([]))},[]);
 const latest=prices[0], avg=prices.length?prices.reduce((a,p)=>a+p.priceUsd,0)/prices.length:0;
 const chart=[...prices].reverse(); const data={labels:chart.map(p=>p.referenceDate),datasets:[{label:'USD/kg',data:chart.map(p=>p.priceUsd),borderColor:'#ff8a1f',backgroundColor:'#ff8a1f22',fill:true,tension:.25}]};
 function csv(){const rows=[['date','country','market','product','category','usd_kg','brl_kg','cny_kg','source','confidence'],...prices.map(p=>[p.referenceDate,p.country,p.market,p.product,p.category,p.priceUsd,p.priceBrl,p.priceCny,p.source,p.confidenceScore])];const blob=new Blob([rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(',')).join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='omip-prices.csv';a.click();URL.revokeObjectURL(a.href)}
 return <ThemeProvider theme={theme}><CssBaseline/><AppBar position="sticky" color="transparent" elevation={0} sx={{backdropFilter:'blur(16px)',borderBottom:1,borderColor:'divider'}}><Toolbar><Box component="span" role="img" aria-label="Laranja" sx={{fontSize:24,lineHeight:1,mr:1.25,filter:'drop-shadow(0 2px 4px rgba(255,138,31,.28))'}}>🍊</Box><Typography fontWeight={800} sx={{flexGrow:1}}>OMIP <Typography component="span" color="text.secondary">Orange Intelligence</Typography></Typography><IconButton onClick={()=>setDark(v=>!v)}>{dark?<LightMode/>:<DarkMode/>}</IconButton></Toolbar></AppBar>
 <Container maxWidth="xl" sx={{py:4}}><Stack spacing={1} mb={4}><Typography variant="overline" color="primary">China-first market monitoring</Typography><Typography variant="h4">Inteligência de mercado da laranja</Typography><Typography color="text.secondary">Cotações normalizadas, rastreáveis e classificadas por confiabilidade.</Typography></Stack>
 {error&&<Alert severity="warning" sx={{mb:3}}>{error}</Alert>}<Stack direction={{xs:'column',sm:'row'}} spacing={2} mb={3}><Chip label="Mercado: China" color="primary" variant="outlined"/><FormControl sx={{minWidth:220}}><InputLabel>Produto</InputLabel><Select value={product} label="Produto" onChange={e=>setProduct(e.target.value)}>{products.map(p=><MenuItem value={p} key={p}>{p||'Todos'}</MenuItem>)}</Select></FormControl><Button startIcon={<FileDownload/>} onClick={csv} disabled={!prices.length}>Exportar CSV</Button></Stack>
 <Grid container spacing={2} mb={3}>{[["Preço atual",latest?`US$ ${latest.priceUsd.toFixed(2)}/kg`:'—'],['Média do período',prices.length?`US$ ${avg.toFixed(2)}/kg`:'—'],['Observações',String(prices.length)],['Confiabilidade',latest?`${latest.confidenceScore}/100`:'—']].map(([l,v])=><Grid size={{xs:12,sm:6,md:4,lg:2}} key={l}><Card sx={{height:'100%'}}><CardContent><Typography color="text.secondary" variant="body2">{l}</Typography><Typography variant="h5" fontWeight={800} mt={1}>{v}</Typography></CardContent></Card></Grid>)}{benchmarks.map(b=><Grid size={{xs:12,sm:6,md:4,lg:2}} key={b.country}><Card sx={{height:'100%'}}><CardContent><Typography color="text.secondary" variant="body2">{b.label}</Typography><Typography variant="h5" fontWeight={800} mt={1}>{b.priceBoxBrl.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</Typography><Typography variant="caption" color="text.secondary" display="block" mt={.75}>{b.referencePeriod}{b.dailyChangePercent!==undefined?` · Dia ${b.dailyChangePercent>0?'+':''}${b.dailyChangePercent.toFixed(2)}%`:''}{b.fiveDayAverage!==undefined?` · Média 5d R$ ${b.fiveDayAverage.toFixed(2)}`:''}</Typography><Button component="a" href={b.url} target="_blank" rel="noreferrer" size="small" sx={{mt:.5,p:0,minWidth:0,textTransform:'none'}}>Fonte: {b.source}</Button></CardContent></Card></Grid>)}</Grid>
 <Grid container spacing={3}><Grid size={{xs:12,lg:7}}><Card><CardContent><Typography variant="h6" mb={2}>Histórico de preços</Typography><Box height={360}><Line data={data} options={{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}}}}/></Box></CardContent></Card></Grid><Grid size={{xs:12,lg:5}}><Card><CardContent><Typography variant="h6" mb={2}>Últimas cotações</Typography><TableContainer sx={{maxHeight:360}}><Table stickyHeader size="small"><TableHead><TableRow><TableCell>Data</TableCell><TableCell>Mercado</TableCell><TableCell align="right">USD/kg</TableCell><TableCell>Fonte</TableCell></TableRow></TableHead><TableBody>{prices.slice(0,20).map(p=><TableRow key={p.id}><TableCell>{p.referenceDate}</TableCell><TableCell>{p.market}</TableCell><TableCell align="right">{p.priceUsd.toFixed(2)}</TableCell><TableCell><Stack direction="row" spacing={1} alignItems="center"><Typography variant="caption">{p.source}</Typography><Chip size="small" label={p.confidenceScore} color={p.confidenceScore>=90?'success':p.confidenceScore>=60?'warning':'default'}/></Stack></TableCell></TableRow>)}</TableBody></Table></TableContainer></CardContent></Card></Grid></Grid>
 <Typography variant="caption" color="text.secondary" display="block" mt={3}>Valores de consenso são médias ponderadas pela confiança. Consulte sempre a fonte e a data de referência antes de decisões comerciais.</Typography>
 <Box component="footer" sx={{mt:4,pt:2.5,borderTop:1,borderColor:'divider',textAlign:'center'}}><Typography variant="caption" color="text.secondary" display="block">© 2026 OMIP — Todos os direitos reservados. By — Lindberg Oliveir.</Typography><Typography component="a" href="https://creativecommons.org/licenses/by-nc/4.0/deed.pt-br" target="_blank" rel="license noreferrer" variant="caption" color="text.secondary" sx={{display:'inline-block',mt:.5}}>Dados CEPEA/ESALQ-USP — CC BY-NC 4.0 — somente uso não comercial</Typography></Box></Container></ThemeProvider>}
export default App;
